Mean Normalization 

In [4]:
import numpy as np
features = np.random.randint(0,10,size =(2,10))

In [14]:
features

array([[3, 6, 6, 9, 4, 7, 4, 8, 2, 1],
       [1, 9, 2, 3, 1, 9, 7, 2, 3, 7]])

In [37]:
def mean_norm(X):
  return np.subtract(X,np.mean(X,axis=1).reshape(-1,1))/(np.max(X,axis=1)-np.min(X,axis=1)).reshape(-1,1)

In [38]:
mean_norm(features)

array([[-0.25 ,  0.125,  0.125,  0.5  , -0.125,  0.25 , -0.125,  0.375,
        -0.375, -0.5  ],
       [-0.425,  0.575, -0.3  , -0.175, -0.425,  0.575,  0.325, -0.3  ,
        -0.175,  0.325]])

In [36]:
X = features

In [28]:
np.mean(X,axis=1),(np.max(X,axis=1)-np.min(X,axis=1))

(array([5. , 4.4]), array([8, 8]))

In [32]:
np.subtract(X,np.mean(X,axis=1).reshape(-1,1))

array([[-2. ,  1. ,  1. ,  4. , -1. ,  2. , -1. ,  3. , -3. , -4. ],
       [-3.4,  4.6, -2.4, -1.4, -3.4,  4.6,  2.6, -2.4, -1.4,  2.6]])

In [34]:
np.mean(X,axis=1).reshape(-1,1).shape

(2, 1)

another way

In [39]:
# create x
x = np.asarray([1,2,3,4], dtype=np.float64)

np.mean(x) # calculates the mean of the array x
x-np.mean(x) # this is euivalent to subtracting the mean of x from each value in x
x-=np.mean(x) # the -= means can be read as x = x- np.mean(x)

np.std(x) # this calcualtes the standard deviation of the array
x/=np.std(x) # the /= means can be read as x = x/np.std(x)

In [40]:
x

array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079])

In [54]:
x = np.asarray([1,2,3,4], dtype=np.float64)

In [55]:
X = np.array([x,[10,20,30,40]])

In [56]:
mean_norm(X)

array([[-0.5       , -0.16666667,  0.16666667,  0.5       ],
       [-0.5       , -0.16666667,  0.16666667,  0.5       ]])

In [57]:
np.std(x)

1.118033988749895

In [58]:
(np.max(x)-np.min(x)).reshape(-1,1)

array([[3.]])

In [59]:
X

array([[ 1.,  2.,  3.,  4.],
       [10., 20., 30., 40.]])

In [63]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

normalized_data = scaler.fit_transform(X)

print(normalized_data)


[[0. 0. 0. 0.]
 [1. 1. 1. 1.]]
